
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 62813
 */
public class soal1 extends javax.swing.JFrame {

    /**
     * Creates new form soal1
     */
    public soal1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        tno = new javax.swing.JTextField();
        tjudul = new javax.swing.JComboBox<>();
        tkode = new javax.swing.JTextField();
        tgenre = new javax.swing.JTextField();
        tpenulis = new javax.swing.JTextField();
        bpinjam = new javax.swing.JButton();
        bkembali = new javax.swing.JButton();
        ttahun = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new java.awt.BorderLayout(15, 15));
        jPanel3.add(jLabel8, java.awt.BorderLayout.LINE_END);

        jLabel9.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 25)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PERPUSTAKAAN");
        jLabel9.setToolTipText("");
        jPanel3.add(jLabel9, java.awt.BorderLayout.PAGE_START);
        jPanel3.add(jLabel10, java.awt.BorderLayout.LINE_START);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Nama              :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("No.Registrasi  :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Judul Buku     :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Kode Buku     :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Genre            :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Penulis          :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Tahun Terbit  :");

        tjudul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Buku", "Aku Banyak Lukanya", "Halaman Terakhir", "Santri Pilihan Bunda", "Rumah Kaca", "Little Women", " ", " " }));
        tjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjudulActionPerformed(evt);
            }
        });

        bpinjam.setText("PINJAM");
        bpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpinjamActionPerformed(evt);
            }
        });

        bkembali.setText("KEMBALIKAN");
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bpinjam)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tnama)
                            .addComponent(tno)
                            .addComponent(tjudul, 0, 163, Short.MAX_VALUE)
                            .addComponent(tkode)
                            .addComponent(tgenre)
                            .addComponent(tpenulis)
                            .addComponent(ttahun))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bkembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tgenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tpenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ttahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpinjam)
                    .addComponent(bkembali)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjudulActionPerformed
        // TODO add your handling code here:
        String judul = tjudul.getSelectedItem().toString();
        
        switch (judul) {
            case "Aku Banyak Lukanya" -> {
                tkode.setText("001");
                tpenulis.setText("Lulux Rofiatul Faidah");
                tgenre.setText("Novel");
                ttahun.setText("2001");
            }
            case "Halaman Terakhir" -> {
                tkode.setText("002");
                tpenulis.setText("Yudhi Herwibowo");
                tgenre.setText("Novel Sejarah");
                ttahun.setText("2002");
            }
            case "Santri Pilihan Bunda" -> {
                tkode.setText("003");
                tpenulis.setText("Salsyabila Falensia");
                tgenre.setText("Novel Islami");
                ttahun.setText("2003");
            }
            case "Rumah Kaca" -> {
                tkode.setText("004");
                tpenulis.setText("Dee Lestari");
                tgenre.setText("Novel Remaja");
                ttahun.setText("2004");
            }
            case "Little Women" -> {
                tkode.setText("005");
                tpenulis.setText("Marah Rusli");
                tgenre.setText("Lousia May ");
                ttahun.setText("2005");
            }
            default -> {
                tkode.setText("-");
            }
        }

    }//GEN-LAST:event_tjudulActionPerformed

    private void bpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpinjamActionPerformed
        // TODO add your handling code here:
        String nama = tnama.getText();
        String no = tno.getText();
        String judul = (String) tjudul.getSelectedItem();
        String kode = tkode.getText();
        String genre = tgenre.getText();
        String penulis = tpenulis.getText();
        String tahun =ttahun.getText();
        
        if (nama.isEmpty() || no.isEmpty() || judul.isEmpty() || kode.isEmpty() ||
        genre.isEmpty() || penulis.isEmpty() || tahun.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harap isi terlebih dahulu.");
    } else {
    
       JOptionPane.showConfirmDialog(this, "TELAH MEMINJAM BUKU" + "\n \n Nama : " + nama + "\n \n No Registrasi: " 
                   + no + "\n \n Judul Buku: " + judul + "\n \n Kode Buku: " + kode + "\n \n Genre Buku: " + genre + 
               "\n \n Pengarang: " + penulis +"\n \n Tahun Terbit :"+ tahun);
        }
       
        tnama.setText("");
        tno.setText("");
        tjudul.setSelectedIndex(0);
        tkode.setText("");
        tgenre.setText("");
        tpenulis.setText("");
        ttahun.setText("");
        
    }//GEN-LAST:event_bpinjamActionPerformed

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        // TODO add your handling code here:
        String nama = tnama.getText();
        String no = tno.getText();
        String judul = (String) tjudul.getSelectedItem();
        String kode = tkode.getText();
        String genre = tgenre.getText();
        String penulis = tpenulis.getText();
        String tahun =ttahun.getText();
        
        if (nama.isEmpty() || no.isEmpty() || judul.isEmpty() || kode.isEmpty() ||
        genre.isEmpty() || penulis.isEmpty() || tahun.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harap isi terlebih dahulu.");
    } else {
   
       JOptionPane.showConfirmDialog(this, "TELAH MENGEMBALIKAN BUKU" + "\n \n Nama : " + nama + "\n \n No Registrasi: " 
                   + no + "\n \n Judul Buku: " + judul + "\n \n Kode Buku: " + kode + "\n \n Genre Buku: " + genre + 
               "\n \n Pengarang: " + penulis +"\n \n Tahun Terbit :"+ tahun);
        }
       
        tnama.setText("");
        tno.setText("");
        tjudul.setSelectedIndex(0);
        tkode.setText("");
        tgenre.setText("");
        tpenulis.setText("");
        ttahun.setText("");
        
    }//GEN-LAST:event_bkembaliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tnama.setText("");
        tno.setText("");
        tjudul.setSelectedIndex(0);
        tkode.setText("");
        tgenre.setText("");
        tpenulis.setText("");
        ttahun.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new soal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkembali;
    private javax.swing.JButton bpinjam;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tgenre;
    private javax.swing.JComboBox<String> tjudul;
    private javax.swing.JTextField tkode;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tno;
    private javax.swing.JTextField tpenulis;
    private javax.swing.JTextField ttahun;
    // End of variables declaration//GEN-END:variables
}
